### ISSUE TITLE
Add support for other scm providers

### ISSUE THREAD

**Issue by garethjevans** [plumming/dx#278]
It would be good to support gitlab.com and internal installs of gitlab, if we could do this, what commands could we support? Should we only support providers that provide a graphql endpoint to reduce traffic?

## Config
How would we restructure the configuration to support different SCM types?

```
repositories:
- name: github.com
  kind: github
  repos:
  - plumming/dx
- name: github.myenterprise.com
  kind: github
  repos:
  - xxx/something
- name: gitlab.com
  kind: gitlab
  repos:
  - another/repo
```

## `dx get prs`
GitLab refers to them as MRs, so adding that as an alias would make sense. I can't find a graphql query to do this in a single shot, may have to perform a request per repository. The following query may be enough to extract enough data for PRs.

```
{
  project(fullPath: "org/repo") {
    mergeRequests(first:50, state:opened) {
      nodes {
        iid
        title
        labels {
          nodes {
            title
          }
        }
        mergeable
        conflicts
        createdAt
        author {
          name
        }
        approvalsRequired
        approvalsLeft
      }
    }
  }
}
```
